name: top_k
version: 1.0.1
description: Returns top k elements from unsorted iterable of comparables.
homepage: https://github.com/jackdreilly/top_k
documentation: https://github.com/jackdreilly/top_k
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  collection: ^1.14.12
dev_dependencies:
  test:
